profiles:
  group:
    test:
      - dev
      - local
      - sample
      - h2
      - base-test
      - azure-vault

---

server:
  port: 8095

#Admin configuration
info:
  name: @app.id@
  description: @app.id@
  version: @pom.version@
  stage: local

#debug: true
client.service.url: http://localhost:8095
spring:
  application:
    id: @app.id@
    name: @app.id@
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/oauth-kk
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      actuator:
        password: easymsActuatorPass!
  cloud:
    config:
      import-check:
        enabled: false
  liquibase:
    change-log: classpath:config/db/db.changelog-master.xml
  profiles.active: dev
  boot:
    admin:
      client:
        url: ${boot.admin.client.url}
        username: ${boot.admin.client.username}
        password: ${boot.admin.client.password}
        instance:
          metadata:
            enable-oauth2: true

jwt:
  auth:
    converter:
      resource-id: oauth-kk-client
      principal-attribute: preferred_username
      jwk-set-uri: http://localhost:8080/realms/oauth-kk/protocol/openid-connect/certs


easyms:
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfig
      enabled: false
  security:
    actuator:
      password: easymsActuatorPass!

management.endpoints.web.exposure.include: "*"

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE

---
spring:
  config:
    activate:
      on-profile: sample

spring.liquibase.contexts: data

---
spring:
  config:
    activate:
      on-profile: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:sdkdb;DB_CLOSE_DELAY=-1
    username: sdk
    password: secret
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
    path: /h2-console

---
spring:
  config:
    activate:
      on-profile: test-base
  jpa:
    hibernate.ddl-auto: none
  h2.console.enabled: false

spring.liquibase.contexts: testData

---
spring:
  config:
    activate:
      on-profile: azure-vault

azure:
  keyvault:
    enabled: false
    uri: https://yourvault.vault.azure.net/
    client-id: yourvault-prinicpal
    tenant-id: yourvault-tenant
    client-key: yourvault-client-key
    token-acquire-timeout-seconds: 60
    refresh-interval: 1800000
