spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${easyms.azure.activedirectory.clientId}
        app-id-uri: ${easyms.azure.activedirectory.appIdUri}
      keyvault:
        secret:
          property-source-enabled: ${easyms.azure.keyvault.enabled}
          property-sources:
            - name: key-vault-property-source
              endpoint: ${easyms.azure.keyvault.endpoint}
              credential:
                client-id: ${easyms.azure.keyvault.clientId}
                client-secret: ${easyms.azure.keyvault.clientSecret}
              profile:
                tenant-id: ${easyms.azure.keyvault.tenant}
  security:
    oauth2:
      client:
        provider:
          azure:
            jwk-set-uri: https://login.microsoftonline.com/${easyms.azure.activedirectory.tenant}/discovery/keys
    user:
      name: ${easyms.security.actuator.user:actuator-admin}
      password: ${easyms.security.actuator.password}
      roles: ACTUATOR

management:
  endpoint:
    health:
      show-details: when-authorized
      roles: ACTUATOR

springdoc:
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${easyms.azure.activedirectory.swaggerclientId}
  oAuthFlow:
    authorizationUrl: https://login.microsoftonline.com/${easyms.azure.activedirectory.tenant}/oauth2/v2.0/authorize
    tokenUrl: https://login.microsoftonline.com/${easyms.azure.activedirectory.tenant}/oauth2/v2.0/token

swagger:
  paths: /api/**
  securityDefinitions:
    oauthSecurity:
      type: oauth2
      tokenUrl: https://login.microsoftonline.com/${easyms.azure.activedirectory.tenant}/oauth2/v2.0/token
      tokenRequestUrl: https://login.microsoftonline.com/${easyms.azure.activedirectory.tenant}/oauth2/v2.0/authorize
      clientId: ${easyms.azure.activedirectory.swaggerclientId}
      scopes: ${easyms.azure.activedirectory.swaggerscopes}

easyms:
  secured:
    azuread :
      enabled: true
      internaltoken:
        enabled: ${easyms.azure.internalToken.enabled:false}
        pubKeyPath : ${easyms.azure.internalToken.pubKeyPath:}
        pubKeyValue : ${easyms.azure.internalToken.pubKeyValue:}
        issuer : ${easyms.azure.internalToken.issuer}

---
spring:
  config.activate.on-profile: test

easyms:
  azure:
    activedirectory:
      tenant: fakeTenant
      clientId: fakeClientId
      appIdUri : fakeAppIdUri
      swaggerclientId: fakeSwaggerClientId
      swaggerscopes: fakeSwaggerScopes

