spring:
  cloud:
    function:
     definition: sendDummy;onDummyReceive
    stream:
      bindings:
        sendDummy-out-0:
          destination: dummy-topic
        onDummyReceive-in-0:
          destination: dummy-topic
      poller:
        fixed-delay: 500