server:
  port: 8091

#Admin configuration
info:
  name: @app.id@
  description: @app.id@
  version: @pom.version@
  stage: local
logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    id: @app.id@
    name: @app.id@
  boot:
    admin:
      client:
        url: http://localhost:2003
        username: admin
        password: admin

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0OIcJ+scLFXw23UtBfhI
          v3jqJ5qIivlZdL3T1gP3qZKaNicPvIVk1ozBJUan1hhUQE1gTI3PGi+Uhjb7zvvP
          GQnPR/nn3SzqtDGus99p5TVpMxNEQuPlMNVTQMcOOeWY2XoPTFFcWHgJJi0M1Fuc
          2KdbodvuT/h5FtRKQeTitAW1O0eZn9WUmYw9BD2N9Ijry3xaoA/rMvNDMWUBYlMH
          sicV/pUxK+t6EnMbUK1N7SHaXzZqEANLwP1ujuXdtJasYBg/Dk+2IIF7IV6MUKFh
          96xO+blmodP8GN+UtRicIHrQkFGuBh/slROluMPZSse0ISYmhJXPTRMNwmffEt/f
          FwIDAQAB
          -----END PUBLIC KEY-----
swagger:
  paths: /api.*
  api.info:
    title: @app.id@
    description: @pom.description@ Documentation
    contact: @swagger.project.contact@
    version: @pom.version@
    license: license
    licenseUrl: http://easyms.fr/LICENSE-0.0.1.html
  security:
    oauth2:
      client:
        clientId: swagger
        clientSecret: secret
  securityDefinitions:
    oauthSecurity:
      type: oauth2
      tokenUrl: http://localhost:2000/oauth/token
      flow: password
      scopes:

easyms:
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfig
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512

management.endpoints.web.exposure.include: "*"

