springdoc:
  show-actuator: true
  swagger-ui:
    client-id: oauth-kk-client
    groups-order: DESC
    use-root-path: true
    default-models-expand-depth: -1
    disable-swagger-default-url: true
    version: '@springdoc-openapi-starter-webmvc-ui.version@'
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
