springdoc:
  show-actuator: false
  swagger-ui:
    oauth:
      client-id: oauth-kk-client
      realm: oauth-kk
    groups-order: DESC
    use-root-path: true
    default-models-expand-depth: -1
    disable-swagger-default-url: true
    csrf:
      enabled: true
    version: '@springdoc-openapi-starter-webmvc-ui.version@'
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
swagger:
  api:
    info:
      title: Easy-ms-Secured
  paths: /api/**