spring:
  cloud:
    azure:
      servicebus:
        namespace: ${easyms.sampleazure.servicebus.namespace}
        resource:
          resource-group: ${easyms.sampleazure.servicebus.resourcegroup}
    function:
      definition: consume;supply;supply2;consumeNew
    stream:
      defaultBinder: servicebus
      bindings:
        consume-in-0:
          destination: mytopic
          group: newsubscription
        consumeNew-in-0:
          destination: mynewtopic
          group: mynewsub
        supply-out-0:
          destination: mytopic
        supply2-out-0:
          destination: mynewtopic
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: false
          consumeNew-in-0:
            consumer:
              auto-complete: false
          supply-out-0:
            producer:
              entity-type: topic
          supply2-out-0:
            producer:
              entity-type: topic
      poller:
        fixed-delay: 1000
        initial-delay: 0
