easyms.spring.cloud.azure.servicebus.credentials.file:
  tenantId: ${easyms.sampleazure.tenantId}
  clientId: ${easyms.sampleazure.servicebus.clientId}
  clientSecret: ${easyms.sampleazure.servicebus.clientSecret}
  subscriptionId: ${easyms.sampleazure.servicebus.subscriptionId}
  activeDirectoryEndpointUrl: "https://login.microsoftonline.com"
  resourceManagerEndpointUrl: "https://management.azure.com/"
  activeDirectoryGraphResourceId: "https://graph.windows.net/"
  sqlManagementEndpointUrl: "https://management.core.windows.net:8443/"
  galleryEndpointUrl: "https://gallery.azure.com/"
  managementEndpointUrl: "https://management.core.windows.net/"

spring:
  cloud:
    azure:
      client-id: ${easyms.sampleazure.servicebus.client-id}
      client-secret: ${easyms.sampleazure.servicebus.client-secret}
      tenant-id: ${easyms.sampleazure.servicebus.tenant-id}
      resource-group: ${easyms.sampleazure.servicebus.resourcegroup}

      #     Uncomment below configurations if you want to enable auto creating resources.
      #
      #      subscription-id: [subscription-id]
      auto-create-resources: true
      #      environment: Azure
      #      region: southcentralus
      region: ${easyms.sampleazure.servicebus.region}
      servicebus:
        namespace: ${easyms.sampleazure.servicebus.namespace}
    stream:
      defaultBinder: servicebus-topic
      bindings:
        consume-in-0:
          destination: mytopic
          group: newsubscription
        consumeNew-in-0:
          destination: mynewtopic
          group: mynewsub
        supply-out-0:
          destination: mytopic
        supply2-out-0:
          destination: mynewtopic
      servicebus:
        topic:
          bindings:
            consume-in-0:
              consumer:
                requeueRejected: true
      #          bindings:

      #            servicebus:
      #                topic:
      #                    bindings:
      #                        consume-in-0:
      #                            consumer:
      #                                checkpoint-mode: MANUAL
      function:
        definition: consume;supply;supply2;consumeNew
      poller:
        fixed-delay: 1000
        initial-delay: 0
